name: MythicMobsPAPI
version: '1.0-Dev'
main: me.blubriu.mythicMobsPAPI.MythicMobsPAPI
api-version: '1.20'
authors: [ BlubRiu ]
description: A plugin should be used for some gamemode
softdepend: [PlaceholderAPI, DecentHolograms]
website: https://blueberry.is-a.dev

commands:
  mmPAPI:
    args: [ mmPapi ]
    description: MythicMobsPAPI
    usage: /mmpapi
    aliases: [ mythicmobspapi ]
